recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
	- applications::git
	- applications::wget
	- applications::pwgen
	- applications::xmlstarlet
	- applications::pv
	- applications::htop
	- dotfiles::gitconfig
	- applications::grunt-cli
	- applications::bower
	- applications::git-flow
	- applications::sass
	- applications::siege
	- applications::ssh_config
	- dotfiles::vim
	- applications::composer
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - nodejs::default                      # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute
	- applications::imageoptim
	- applications::imagealpha
	- applications::svgo
	- applications::sublime_text_3
	- applications::phpstorm
	- applications::codekit
	- applications::espresso
	- applications::watch
	- applications::gnu-tar
	- applications::sequelpro
	- applications::sourcetree
	- osxdefaults::set_terminal_profile
	- osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
	- osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
	- osxdefaults::enable_safari_debug_menu
	- osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
attributes:
    homebrewalt:
        apps:
            - git
        cask_apps:
            - google-chrome
    nodejs:
        apps:
            - bower